import React,{useEffect,useRef,useState} from 'react';
import {createClient} from 'genlayer-js';
import {studionet} from 'genlayer-js/chains';
import {TransactionStatus} from 'genlayer-js/types';
import {Activity,AlertTriangle,CheckCircle2,ExternalLink,RefreshCw,RotateCcw,Search,ShieldCheck,Wallet} from 'lucide-react';

const CONTRACT=import.meta.env.VITE_CONTRACT_ADDRESS||'';
const configured=/^0x[a-fA-F0-9]{40}$/.test(CONTRACT);
const BOND=10n**15n;
const labels=['WATCHING','SUBMITTED','RECALL MATCH','NO MATCH','UNCERTAIN','TERMINATED / REMEDIATED'];
const short=(v='')=>v.length>16?`${v.slice(0,8)}…${v.slice(-6)}`:v;
const rpc=()=>createClient({chain:studionet});
const parse=async(name,args=[])=>JSON.parse(await rpc().readContract({address:CONTRACT,functionName:name,args}));

export default function App(){
 const [account,setAccount]=useState(''),[watches,setWatches]=useState([]),[subs,setSubs]=useState([]),[stats,setStats]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[hash,setHash]=useState('');
 const [watchForm,setWatchForm]=useState({distributor:'',category:'FOOD',manufacturer:'',product:'',identifier:''});
 const [noticeForm,setNoticeForm]=useState({watchId:'0',noticeId:''});const lock=useRef(false);
 async function refresh(){if(!configured)return;const c=await parse('get_counts');const ws=await Promise.all(Array.from({length:Number(c.watch_count)},(_,i)=>parse('get_watch',[BigInt(i)])));const ss=await Promise.all(Array.from({length:Number(c.submission_count)},(_,i)=>parse('get_submission',[BigInt(i)])));setWatches(ws);setSubs(ss);setStats(await parse('get_accounting'))}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message));const eth=window.ethereum;const update=a=>setAccount(a?.[0]||'');eth?.request({method:'eth_accounts'}).then(update).catch(()=>{});eth?.on?.('accountsChanged',update);return()=>eth?.removeListener?.('accountsChanged',update)},[]);
 async function connect(){try{if(!window.ethereum)throw new Error('Install a compatible wallet first.');const a=await window.ethereum.request({method:'eth_requestAccounts'});setAccount(a[0]||'')}catch(e){setMessage(e.message)}}
 async function write(functionName,args,value){if(lock.current)return;lock.current=true;setBusy(true);setHash('');try{if(!configured)throw new Error('Deploy the contract and configure VITE_CONTRACT_ADDRESS first');if(!account)throw new Error('Connect your wallet first');if(BigInt(await window.ethereum.request({method:'eth_chainId'}))!==61999n)throw new Error('Switch the wallet to GenLayer Studionet (chain 61999)');const c=createClient({chain:studionet,provider:window.ethereum,account});setMessage(`Confirm ${functionName} in your wallet.`);const tx=await c.writeContract({address:CONTRACT,functionName,args,...(value?{value}:{})});setHash(tx);localStorage.setItem(`recall:${CONTRACT}:${account}`,tx);setMessage('Submitted. Waiting for finality; do not send a duplicate.');await rpc().waitForTransactionReceipt({hash:tx,status:TransactionStatus.FINALIZED});await refresh();setMessage('Finalized. The cards below were re-read from the contract; inspect the transaction return value for the exact business result.');localStorage.removeItem(`recall:${CONTRACT}:${account}`)}catch(e){setMessage(`${e.message}. If a hash was issued, inspect it before retrying.`)}finally{lock.current=false;setBusy(false)}}
 async function createWatch(e){e.preventDefault();await write('register_watch',[watchForm.distributor,watchForm.category,watchForm.manufacturer,watchForm.product,watchForm.identifier])}
 async function report(e){e.preventDefault();const w=watches.find(x=>Number(x.watch_id)===Number(noticeForm.watchId));if(!w||![0,3,5].includes(Number(w.state)))return setMessage('Select a watch that is open for a new notice.');await write('submit_notice',[BigInt(w.watch_id),`FDA_${w.category}`,noticeForm.noticeId],BOND)}
 const latest=w=>Number(w.state)===0?undefined:subs.find(s=>Number(s.submission_id)===Number(w.current_submission));
 const openWatches=watches.filter(w=>[0,3,5].includes(Number(w.state)));
 const recoverable=subs.filter(s=>account&&s.reporter?.toLowerCase()===account.toLowerCase()&&[2,3,5].includes(Number(s.state))&&BigInt(s.bond_wei)>0n);
 return <div className="shell"><header><a className="brand" href="#top"><img src="/recall-sentinel-logo.png" alt="Public Recall Sentinel logo"/><div><b>Public Recall Sentinel</b><span>Authority-bound product intelligence</span></div></a><nav><a href="#desk">Operations</a><a href="#method">Method</a></nav><div className="wallets"><span>Studionet · 61999</span><button onClick={connect}><Wallet size={16}/>{account?short(account):'Connect wallet'}</button></div></header>
 <main id="top"><section className="hero"><div><p className="kicker"><ShieldCheck size={16}/> PUBLIC-SOURCE VERIFICATION</p><h1>Know when a recall<br/><em>actually matches.</em></h1><p className="lead">Register a product watch, report an FDA recall number, and let GenLayer validators retrieve the canonical record and judge product identity independently.</p><a className="cta" href="#desk">Open investigation desk <Search size={17}/></a></div><img className="hero-logo" src="/recall-sentinel-logo.png" alt=""/></section>
 <section className="metrics"><div><Activity/><span>Product watches<strong>{watches.length}</strong></span></div><div><AlertTriangle/><span>Confirmed matches<strong>{watches.filter(w=>Number(w.state)===2).length}</strong></span></div><div><RotateCcw/><span>Active reporter bonds<strong>{stats.active_bonds||'0'} wei</strong></span></div><button disabled={busy||!configured} onClick={()=>refresh().catch(e=>setMessage(e.message))}><RefreshCw size={16}/> Refresh on-chain</button></section>
 <section id="desk" className="desk"><div className="section-head"><div><p className="kicker">INVESTIGATION DESK</p><h2>Register, report, verify</h2></div><span className={`config ${configured?'ok':''}`}>{configured?`Contract ${short(CONTRACT)}`:'Awaiting deployment'}</span></div>
 {message&&<div className="message" role="status">{message}{hash&&<> · <a href={`https://explorer-studio.genlayer.com/transactions/${hash}`} target="_blank" rel="noreferrer">Inspect transaction <ExternalLink size={13}/></a></>}</div>}
 <div className="forms"><form onSubmit={createWatch}><span className="step">01 / PRODUCT WATCH</span><h3>Define the identity boundary</h3><label>Distributor wallet<input required pattern="0x[a-fA-F0-9]{40}" value={watchForm.distributor} onChange={e=>setWatchForm({...watchForm,distributor:e.target.value})} placeholder="0x…"/></label><div className="row"><label>Authority category<select value={watchForm.category} onChange={e=>setWatchForm({...watchForm,category:e.target.value})}><option>FOOD</option><option>DRUG</option></select></label><label>Lot / UPC / NDC<input required value={watchForm.identifier} onChange={e=>setWatchForm({...watchForm,identifier:e.target.value})} placeholder="LOT-A7"/></label></div><label>Manufacturer<input required value={watchForm.manufacturer} onChange={e=>setWatchForm({...watchForm,manufacturer:e.target.value})} placeholder="Legal manufacturer name"/></label><label>Product description<input required value={watchForm.product} onChange={e=>setWatchForm({...watchForm,product:e.target.value})} placeholder="Product and package size"/></label><button className="submit" disabled={busy||!configured}>Register watch</button></form>
 <form onSubmit={report}><span className="step">02 / RECALL REPORT</span><h3>Bind a canonical notice</h3><label>Watch<select value={noticeForm.watchId} onChange={e=>setNoticeForm({...noticeForm,watchId:e.target.value})}>{openWatches.map(w=><option key={w.watch_id} value={w.watch_id}>#{w.watch_id} · {w.product}</option>)}</select></label><label>FDA recall number<input required value={noticeForm.noticeId} onChange={e=>setNoticeForm({...noticeForm,noticeId:e.target.value})} placeholder="F-2026-1001"/></label><div className="source"><ShieldCheck/><p><b>Source is derived—not submitted</b><br/>The contract constructs an exact api.fda.gov query from the selected category and recall number.</p></div><p className="bond">Reporter bond: <b>0.001 GEN</b> · returned after a terminal assessment.</p><button className="submit danger" disabled={busy||!configured||!openWatches.length}>Report recall</button></form></div>
 {!configured?<div className="empty"><ShieldCheck/><h3>Ready for a fresh deployment</h3><p>No fallback address is embedded. Deploy this reviewed source, then set the environment address and rebuild.</p></div>:!watches.length?<div className="empty"><Search/><h3>No watches registered</h3><p>Create the first identity-bound product watch above.</p></div>:<div className="watch-grid">{watches.map(w=>{const s=latest(w);const mine=account&&s?.reporter?.toLowerCase()===account.toLowerCase();return <article className={`watch state-${w.state}`} key={w.watch_id}><div className="watch-top"><span>WATCH #{w.watch_id} · {w.category}</span><b>{labels[Number(w.state)]}</b></div><h3>{w.product}</h3><p>{w.manufacturer} · <code>{w.identifier}</code></p><dl><div><dt>Distributor</dt><dd>{short(w.distributor)}</dd></div><div><dt>Verdict</dt><dd>{w.verdict}</dd></div><div><dt>Recall</dt><dd>{s?.notice_id||'—'}</dd></div><div><dt>Assessments</dt><dd>{s?.assessment_count||0}</dd></div></dl>{s&&<a className="canonical" href={s.source_url} target="_blank" rel="noreferrer">Canonical FDA query <ExternalLink size={14}/></a>}<div className="actions">{s&&[1,4].includes(Number(w.state))&&<button disabled={busy} onClick={()=>write('assess_notice',[BigInt(s.submission_id)])}>Assess / retry</button>}{Number(w.state)===2&&<button disabled={busy} onClick={()=>write('verify_remediation',[BigInt(w.watch_id)])}>Check termination</button>}{s&&mine&&[2,3,5].includes(Number(w.state))&&BigInt(s.bond_wei)>0n&&<button disabled={busy} onClick={()=>write('return_bond',[BigInt(s.submission_id)])}>Return my bond</button>}</div></article>})}</div>}
 {recoverable.length>0&&<div className="bond-tray"><div><b>Recoverable reporter bonds</b><span>Includes older terminal submissions that are no longer current.</span></div>{recoverable.map(s=><button key={s.submission_id} disabled={busy} onClick={()=>write('return_bond',[BigInt(s.submission_id)])}>Return bond #{s.submission_id}</button>)}</div>}
 </section><section id="method" className="method"><p className="kicker">WHY GENLAYER</p><h2>Public facts change. Settlement must remain deterministic.</h2><div><article><span>1</span><h3>Authority binding</h3><p>Users provide a recall ID, never an arbitrary evidence URL. Category fixes the approved FDA endpoint.</p></article><article><span>2</span><h3>Independent retrieval</h3><p>Every validator fetches the same canonical record and checks the exact recall number before semantic review.</p></article><article><span>3</span><h3>Closed consensus</h3><p>Semantic output is reduced to MATCH, NO_MATCH or UNCERTAIN. Source failure cannot become a positive match.</p></article></div></section></main><footer><span>PublicRecallSentinel · GenLayer Studionet</span><span>Testnet demonstration—not a substitute for official safety guidance.</span></footer></div>;
}
